#!/usr/bin/env python3
"""
Generate a document's section 15 anchor index from the anchors it already uses.

Section 15 exists so a rebase can be reconciled mechanically: it lists every
anchor in the document beside the symbol it names. Deriving it from the
document's own text guarantees it stays complete, which hand-maintenance across
a thousand-line document does not.

The symbol for each anchor is read from the pinned revision, so the index
describes the documented revision rather than the working tree.

Usage:
    python _scripts/make_anchor_index.py 11          # print the table
    python _scripts/make_anchor_index.py 11 --apply  # append or replace section 15
"""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
DOCS = HERE.parent
REPO = DOCS.parents[1]
PIN = "70a8f4fe1"

ANCHOR_RE = re.compile(r"`(idaes/[A-Za-z0-9_./-]+\.(?:py|json|csv|nl|svg|md|txt))(?::(\d+))(?:-(\d+))?`")
SECTION15_RE = re.compile(r"\n## 15\..*\Z", re.DOTALL)

DEF_RE = re.compile(r"^\s*(?:async\s+)?(?:def|class)\s+([A-Za-z_][A-Za-z0-9_]*)")
ASSIGN_RE = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=")
DECLARE_RE = re.compile(r"""\.declare\(\s*["']([^"']+)["']""")


def source_at_pin(rel: str) -> list[str] | None:
    proc = subprocess.run(["git", "show", f"{PIN}:{rel}"], cwd=REPO, capture_output=True)
    if proc.returncode != 0:
        return None
    return proc.stdout.decode("utf-8", errors="replace").splitlines()


def describe(lines: list[str], n: int) -> str:
    """Name what lives at line n, using the source itself."""
    if not (1 <= n <= len(lines)):
        return "—"
    line = lines[n - 1]
    m = DEF_RE.match(line)
    if m:
        return f"`{m.group(1)}`"
    m = DECLARE_RE.search(line)
    if m:
        return f"`{m.group(1)}` config key"
    m = ASSIGN_RE.match(line)
    if m:
        return f"`{m.group(1)}`"
    stripped = line.strip()
    if stripped.startswith(("@", "raise", "if", "for", "return", "try", "with")):
        return stripped[:60]
    return stripped[:60] or "—"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("doc", help="document number, e.g. 11 or 08a")
    ap.add_argument("--apply", action="store_true", help="write section 15 into the file")
    args = ap.parse_args()

    matches = sorted(DOCS.glob(f"{args.doc}*.md"))
    if len(matches) != 1:
        print(f"expected exactly one document matching {args.doc!r}, found {len(matches)}")
        return 1
    path = matches[0]
    text = path.read_text(encoding="utf-8")

    body = SECTION15_RE.sub("", text)
    seen: dict[tuple[str, int], None] = {}
    for m in ANCHOR_RE.finditer(body):
        seen[(m.group(1), int(m.group(2)))] = None

    cache: dict[str, list[str] | None] = {}
    rows = []
    for rel, line in sorted(seen):
        if rel not in cache:
            cache[rel] = source_at_pin(rel)
        src = cache[rel]
        sym = describe(src, line) if src else "— (not present at the pinned revision)"
        rows.append(f"| `{rel}:{line}` | {sym} |")

    table = "\n".join(
        ["## 15. Source anchor index", "",
         f"Every anchor used in this document, with the symbol it names at "
         f"`{PIN}`. Generated by `_scripts/make_anchor_index.py`.", "",
         "| Anchor | Symbol |", "|---|---|", *rows, ""]
    )

    if not args.apply:
        print(table)
        print(f"\n({len(rows)} distinct anchors)")
        return 0

    path.write_text(body.rstrip() + "\n\n---\n\n" + table, encoding="utf-8")
    print(f"wrote section 15 to {path.name} ({len(rows)} anchors)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
